# Generated by Django 6.0.7 on 2026-07-13 06:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Nömrə ən azı 9 rəqəmdən ibarət olmalıdır, yalnız rəqəm yazın', regex='^\\d{9,15}$')]),
        ),
    ]
